server:
  port: 8092

spring:
  application:
    name: hotel-service

  datasource:
    url: jdbc:h2:mem:hotels_db
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      settings.trace: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: db/changelog/changelog-master.xml

springdoc:
  override-with-generic-response: false

